site_iD: "4"
site_name: "MediaCoreService"
site_description: "\"A service to implement Local Storage/USB/IAP2/MTP/BTIAP2/ CarPlay/AndroidAuto/CarLife/Alexa media sources audio playback.  Support Local Storage/USB/MTP sources video playback and image browser.  Support global search.\""
site_version: "platform-t-mainline"
site_status: "Active"
site_la: "Media MediaPlayer"
site_responsible: {"name":"Li, Xi ; Lappa","email":"Xi.Li@harman.com"}
site_architects: {"name":"Wang, Yong","email":"Yong.Wang@harman.com"}
site_last_review_date: 
site_asil: "ASIL QM"
site_permissions: "Restricted"
site_price: {"currency":"USD","amount":"40"}
site_license: "perpetual license"
site_artifact: "APK"
site_layer: "Middleware"
site_Domain: "Media"
site_environment: "Embedded"
site_requirements: ["https://alm.harman.com/rm/resources/bc9a6ab2-4d79-4367-9d45-8c75e2a1d81f?oslc_config.context=https%3A%2F%2Falm.harman.com%2Fgc%2Fconfiguration%2F1696"]
site_designdocuments: ["EA document path https://subversion.harman.com/svn/digital-cockpit-ea","Node path to HDD /Digital Cockpit/Titan IVI/TITAN DOMAINS/Media/HDD/MediaCoreService/HDD - Android S&T","Node path to CDD /Digital Cockpit/Titan IVI/TITAN DOMAINS/Media/CDD/MediaCoreService - Android S&T"]
site_subcomponents: ["LocalPlayer","IAP2Player","CarPlayPlayer","AndrodAutoPlayer","CarLifePlayer","OnlineStreamingPlayer","MediaContentProvider"]
site_releasenotes: ["https://androidhub.harman.com/q/project:harman/packages/MediaCoreService+status:merged+branch:platform-t-mainline+"]
site_resourceutilization: ["https://confluence.harman.com/confluence/pages/viewpage.action?pageId=192458850"]
site_interface: ["https://confluence.harman.com/confluence/pages/viewpage.action?pageId=192458850"]
site_interfaceconsumed: ["\"harman.iap2 harman.aap harman.carplay harman.onlineplayer HarmanUsbHandlerManager Hlog MediaModeManager OnlinePlayer HarmanAudioManager\""]
site_runtimedependencies: ["\"IAP2Service AndroidAutoApp CarPlayApp HarmanUsbService MediaModeService HarmanAudioService\""]
site_buildtimedependencies: ["\"harman.iap2 harman.aap harman.carplay harman.onlineplayer HarmanUsbHandlerManager Hlog MediaModeManager OnlinePlayer HarmanAudioManager\""]
site_repositories: ["https://androidhub.harman.com/admin/repos/harman/packages/MediaCoreService,general"]
site_foss: []
site_supportedos: ["Android"]
site_buildinstructions: ["make MediaCoreService"]
site_origin: []
site_activity: "https://androidhub.harman.com/q/project:harman/packages/MediaCoreService+status:merged+branch:platform-t-mainline+"
site_vulnerabilities: ["https://codesonar-preintegration-idc.harman.com:7340/project/756.html"]
site_codelanguage: "Java"
site_i18n: "en ar de es ja ko ro ru w820dp zh-rCN zh-rHK zh-rTW"
site_testcode: ["https://ss-t.harman.com/xref/platform-t/Android/vendor/harman/packages/MediaCoreService/harmanmediaservice/src/test/"]
site_testdocumentations: ["https://artifactory-mb.harman.com/artifactory/Titan/precheck/platform-s/platform_s_precheck_pipeline/AudiGLToTitanMainline_S/7392/"]
site_forking: "Not Allowed"


nav:
  - Asset Metadata: index.md

plugins:
  - techdocs-core
